script:
  - bash ./scripts/deploy-to-gh-pages.sh
env:
  global:
   - GITHUB_REPO: "shawn11ZX/softRasterization"
   - secure: XKBkNBjDw2zTlMx20f/hg/kEEbp+aEjGwvKNfB9v9d7L+i40WiJJD2MzXXSp4YZRNimw1WaMvjG5YDws46Sh4nQhmhNIc/Gocq2JE5RaPHY8iHlgRbUBBFaWzUYtkuWoNldFV8Mw4qYxVlL+7BL6o7riBo2s+yf5E1tBUPw2fsF2RjXpFvupEyZ8Vr8oGtmx/fxOFdeyPRJlIgxQnrvlvc4/14zvQYmRRTInSUKH1ktIZZ22jl7KXvya6wPTUW8UmmSmBSZdi580H7OwQP9SKI2+TAOR8ZzUALFjFceJPHjmmo9Pphh9TshKSCrFIiL40kwTPc4pfSuMxbU7xsFniqwHQ6fwlhSaWGY2S6qe61S/a4CdwRr52akDK6ARBXYSawkssEzlFTpEZomAojhPFJpkGrIRlFHmiWV53oGgjnuLWdjSJr/E8WVmi+sSkDIJt1gyI7Ooc6LGt7SRCQK9SJWxQW0zvX68VviClxvfQ7lvH1wM0qO23wKtzvOG7KA58UICAaVb1GIGon1TJRZvK4UB9R2l2yVAF7U/Y5zUpJqgybuHz8r3hKQgGa5ziFP/Bam3VjkP7bzcbM5qTx7ocxzWVGZoIM0rt//qC6Cw6yFBhE0RMwzCXAyeXPUVSbPVLGIvos4xUsGrvgLQbZr4wwKzAhIYqVlGsZC47n/g8Ug=
