script:
- bash ./scripts/deploy-to-gh-pages.sh
env:
  global:
  - GITHUB_REPO: shawn11ZX/softRasterization
  - secure: j/x4LCeQnNgD7YOOWl6elUMEe91qAZuvfDHE1SZD4YEd3cMipQyahz/q5k05+5wLO/mFtusn/79nmMbWF81YjeQm/TIC+REkmbFCuM2UWTNNSglOF2PPhOiH2E4UAG/xRqRxCPwFAQk0j1Bg6pAWXB9uh0SkeXp6PEABvUpjDdroQUmzsdQw+hbcN7G8gBinlv/NjMk98NfIw+j7vHNWwA/4xvAVvN1soLUq4+ST6mLgfSx8Y9fOYw7SDmTruhWMdgvc11GtuIRGR5KPpmshEiVp6KJD0ArEX91n5aX1GLn3kGUF/TCfmmR1pOVzhKDNE3AIcNqcWj0NLvfVdUbv8/Pj/gCoC3QJ3UoUBwOh5kO3O3Z2nHPL0fvJPyBeAKiD83EwUKUGv5yBBENDN7WEVP8LTwvyYHfjjZXI/aubaeHW8E23GizyOS8jUx48vvOgy6/gxkW19Y63ymXHMAFTcmCwsChNeeMcHc/fCcrwhsdxlgepEJ4UI0yGNdRvA5b/dvS4GDncZx9nuCCxae0Dbi7uAwCBe1EK40yCSHMruEuvSGcimWsIQ7+usp/8dx5a1QR8R8vq+jUV2LAoAlyJrfJv6aehJFs98/H3Q/W5rfI+7jOzeLfRZPvZ/PzvDy61V8KgRAenYPXH0/DRq/1ePdwILw8yySk824fA+CtRt+c=
